[package]
name = "example-yaml-parser"
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
thiserror = "1.0.61"
yaml-rust = "0.4.5"
